[chain]
chain_id = 4663
name = "Ethereum Mainnet"
rpc_urls = ["https://robinhood-mainnet.g.alchemy.com/v2/alch_dnp1_GGicKNXi_gJI6rV9"]
mev_builder_urls = [
    "https://relay.flashbots.net",
    "https://rpc.titanbuilder.xyz",
]
rpc_timeout_ms = 2000

[drop]
target_contract = "0x31647d241c328f46ca3a3d3c9fc1588210a08636"
mint_function = "mint(uint256)"
mint_value_wei = "0"
flip_function_signatures = [
    "isPublicSaleActive()",
    "publicSaleActive()",
    "saleIsActive()",
]

[gas]
max_fee_gwei = 3.0
max_priority_fee_gwei = 3.0
gas_limit = 150000
auto_speedup = true
speedup_threshold_ms = 12000
speedup_bump_percent = 15
hard_gas_ceiling_gwei = 150.0

[alerts]
